# Generated by Django 3.1.1 on 2020-10-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacture_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_type', models.CharField(choices=[('A Check', 'A Check'), ('B Check', 'B Check'), ('C Check', 'C Check'), ('3C Check', '3C Check'), ('D Check', 'D Check')], default='A Check', max_length=200)),
                ('Service_Price', models.CharField(default='0USD', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraftmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aircraft_name', models.CharField(max_length=200, unique=True)),
                ('Aircraft_model', models.CharField(max_length=200, unique=True)),
                ('Aircraft_seats', models.IntegerField()),
                ('Aircraft_length', models.CharField(max_length=200)),
                ('Aircraft_wingspan', models.CharField(max_length=200)),
                ('Aircraft_fuel', models.CharField(max_length=200)),
                ('Aircraft_ceiling', models.CharField(max_length=200)),
                ('Aircraft_range', models.CharField(max_length=200)),
                ('Aircraft_engine', models.CharField(choices=[('PW4000', 'PW4000'), ('GE90', 'GE90'), ('RR Trent800', 'RR Trent800')], default='PW4000', max_length=200)),
                ('Aircraft_price', models.CharField(default='150 Million', max_length=200)),
                ('Aircraft_image', models.ImageField(upload_to='')),
                ('Aircraft_manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeadmin.manufacture')),
            ],
        ),
    ]
