# Generated by Django 3.1.1 on 2020-10-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeadmin', '0002_auto_20201007_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmodels',
            name='Aircraft_engine',
            field=models.CharField(choices=[('PW4000', 'PW4000'), ('GE90', 'GE90'), ('RR Trent800', 'RR Trent800')], default='GE90', max_length=200),
        ),
    ]
