# Generated by Django 3.1.1 on 2020-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeadmin', '0003_auto_20201007_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
