# Generated by Django 3.1.1 on 2020-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeadmin', '0005_auto_20201007_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmodels',
            name='Aircraft_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
