# Generated by Django 3.1.1 on 2020-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeadmin', '0006_auto_20201008_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='Manufacture_image',
            field=models.ImageField(default='None', upload_to='images'),
        ),
    ]
